<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $proveedores = [
            ['nombre' => 'MedSupply Central', 'telefono' => '7718001001', 'contacto' => 'Ana Lopez'],
            ['nombre' => 'Laboratorios Delta', 'telefono' => '7718001002', 'contacto' => 'Marco Ruiz'],
            ['nombre' => 'ClinicaPro Distribuciones', 'telefono' => '7718001003', 'contacto' => 'Laura Soto'],
            ['nombre' => 'BioSafe EPP', 'telefono' => '7718001004', 'contacto' => 'Carlos Mendez'],
            ['nombre' => 'Ortopedia Drive', 'telefono' => '7718001005', 'contacto' => 'Roberto Vega'],
            ['nombre' => 'Terapia Avanzada', 'telefono' => '7718001006', 'contacto' => 'Sofia Ruiz'],
            ['nombre' => 'Equipos Respiratorios Pro', 'telefono' => '7718001007', 'contacto' => 'Miguel Torres'],
            ['nombre' => 'Audición Plus', 'telefono' => '7718001008', 'contacto' => 'Patricia Gomez'],
        ];

        foreach ($proveedores as $proveedor) {
            DB::table('proveedores')->updateOrInsert(
                ['nombre' => $proveedor['nombre']],
                [
                    'telefono' => $proveedor['telefono'],
                    'contacto' => $proveedor['contacto'],
                    'updated_at' => now(),
                    'created_at' => now(),
                ]
            );
        }

        $categoriaIds = DB::table('categorias')->pluck('id', 'nombre');
        $proveedorIds = DB::table('proveedores')->pluck('id', 'nombre');

        $imagenes = [
            'productos/linahp-01.webp',
            'productos/linahp-02.webp',
            'productos/linahp-03.webp',
            'productos/linahp-04.webp',
            'productos/linahp-05.webp',
            'productos/linahp-06.webp',
            'productos/linahp-07.webp',
            'productos/linahp-08.webp',
            'productos/linahp-09.webp',
            'productos/linahp-10.webp',
            'productos/linahp-11.webp',
            'productos/linahp-12.webp',
        ];

        $productos = [
            [
                'categoria' => 'EPP',
                'proveedor' => 'BioSafe EPP',
                'nombre' => 'Guantes de latex talla M (caja x100)',
                'sku' => 'EPP-GUANTES-M',
                'codigo_barras' => '7501001000011',
                'unidad_medida' => 'caja',
                'precio_compra' => 45.00,
                'precio_venta' => 65.00,
                'stock_actual' => 12,
                'stock_minimo' => 20,
                'tiene_caducidad' => false,
            ],
            [
                'categoria' => 'Material de Curacion',
                'proveedor' => 'ClinicaPro Distribuciones',
                'nombre' => 'Gasa esteril 10x10 paquete x100',
                'sku' => 'CUR-GASA-10X10',
                'codigo_barras' => '7501001000028',
                'unidad_medida' => 'caja',
                'precio_compra' => 12.00,
                'precio_venta' => 18.00,
                'stock_actual' => 9,
                'stock_minimo' => 15,
                'tiene_caducidad' => true,
            ],
            [
                'categoria' => 'Diagnostico',
                'proveedor' => 'MedSupply Central',
                'nombre' => 'Termometro digital infrarrojo',
                'sku' => 'DIA-TERM-001',
                'codigo_barras' => '7501001000035',
                'unidad_medida' => 'pieza',
                'precio_compra' => 95.00,
                'precio_venta' => 140.00,
                'stock_actual' => 7,
                'stock_minimo' => 10,
                'tiene_caducidad' => false,
            ],
            [
                'categoria' => 'Diagnostico',
                'proveedor' => 'MedSupply Central',
                'nombre' => 'Oximetro de pulso digital',
                'sku' => 'DIA-OXI-001',
                'codigo_barras' => '7501001000042',
                'unidad_medida' => 'pieza',
                'precio_compra' => 520.00,
                'precio_venta' => 780.00,
                'stock_actual' => 6,
                'stock_minimo' => 5,
                'tiene_caducidad' => false,
            ],
            [
                'categoria' => 'Desinfectantes',
                'proveedor' => 'ClinicaPro Distribuciones',
                'nombre' => 'Alcohol isopropilico 70% 1L atomizador',
                'sku' => 'DES-ALC-1L',
                'codigo_barras' => '7501001000059',
                'unidad_medida' => 'pieza',
                'precio_compra' => 45.00,
                'precio_venta' => 68.00,
                'stock_actual' => 4,
                'stock_minimo' => 8,
                'tiene_caducidad' => true,
            ],
            [
                'categoria' => 'Medicamentos',
                'proveedor' => 'Laboratorios Delta',
                'nombre' => 'Solucion salina 0.9% 500ml bolsa',
                'sku' => 'MED-SS-500',
                'codigo_barras' => '7501001000066',
                'unidad_medida' => 'pieza',
                'precio_compra' => 28.00,
                'precio_venta' => 40.00,
                'stock_actual' => 14,
                'stock_minimo' => 12,
                'tiene_caducidad' => true,
            ],
            [
                'categoria' => 'Dispositivos Medicos',
                'proveedor' => 'MedSupply Central',
                'nombre' => 'Jeringa 5ml estéril individual',
                'sku' => 'DIS-JER-5ML',
                'codigo_barras' => '7501001000073',
                'unidad_medida' => 'pieza',
                'precio_compra' => 2.20,
                'precio_venta' => 3.80,
                'stock_actual' => 60,
                'stock_minimo' => 40,
                'tiene_caducidad' => false,
            ],
            [
                'categoria' => 'Insumos Quirurgicos',
                'proveedor' => 'ClinicaPro Distribuciones',
                'nombre' => 'Bata desechable quirúrgica SMS',
                'sku' => 'QUI-BATA-DES',
                'codigo_barras' => '7501001000080',
                'unidad_medida' => 'pieza',
                'precio_compra' => 18.00,
                'precio_venta' => 28.00,
                'stock_actual' => 25,
                'stock_minimo' => 20,
                'tiene_caducidad' => false,
            ],
            [
                'categoria' => 'Dispositivos Medicos',
                'proveedor' => 'MedSupply Central',
                'nombre' => 'Tensiometro de brazo digital',
                'sku' => 'DIS-TENS-001',
                'codigo_barras' => '7501001000097',
                'unidad_medida' => 'pieza',
                'precio_compra' => 320.00,
                'precio_venta' => 499.00,
                'stock_actual' => 15,
                'stock_minimo' => 8,
                'tiene_caducidad' => false,
            ],
            [
                'categoria' => 'Diagnostico',
                'proveedor' => 'MedSupply Central',
                'nombre' => 'Glucometro portatil con tiras',
                'sku' => 'DIA-GLUC-001',
                'codigo_barras' => '7501001000103',
                'unidad_medida' => 'pieza',
                'precio_compra' => 210.00,
                'precio_venta' => 349.00,
                'stock_actual' => 10,
                'stock_minimo' => 6,
                'tiene_caducidad' => false,
            ],
            [
                'categoria' => 'Ortopedia y Movilidad',
                'proveedor' => 'Ortopedia Drive',
                'nombre' => 'Andadera Ortopedica Plegable con Altura Ajustable',
                'sku' => 'ORT-AND-001',
                'codigo_barras' => '7501001000110',
                'unidad_medida' => 'pieza',
                'precio_compra' => 651.00,
                'precio_venta' => 999.00,
                'stock_actual' => 8,
                'stock_minimo' => 4,
                'tiene_caducidad' => false,
            ],
            [
                'categoria' => 'Ortopedia y Movilidad',
                'proveedor' => 'Ortopedia Drive',
                'nombre' => 'Andadera Rollator Adulto Plegable con Asiento',
                'sku' => 'ORT-ROLL-001',
                'codigo_barras' => '7501001000127',
                'unidad_medida' => 'pieza',
                'precio_compra' => 1548.00,
                'precio_venta' => 2299.00,
                'stock_actual' => 5,
                'stock_minimo' => 2,
                'tiene_caducidad' => false,
            ],
            [
                'categoria' => 'Ortopedia y Movilidad',
                'proveedor' => 'Ortopedia Drive',
                'nombre' => 'Agarradera Barra De Succion Seguridad Baño',
                'sku' => 'ORT-AGARR-001',
                'codigo_barras' => '7501001000134',
                'unidad_medida' => 'pieza',
                'precio_compra' => 1200.00,
                'precio_venta' => 1747.00,
                'stock_actual' => 11,
                'stock_minimo' => 6,
                'tiene_caducidad' => false,
            ],
            [
                'categoria' => 'Rehabilitacion',
                'proveedor' => 'Terapia Avanzada',
                'nombre' => 'Almohadilla Cojin Termica Electrica Dolores Musculares',
                'sku' => 'REHAB-ALMO-001',
                'codigo_barras' => '7501001000141',
                'unidad_medida' => 'pieza',
                'precio_compra' => 409.00,
                'precio_venta' => 599.00,
                'stock_actual' => 13,
                'stock_minimo' => 5,
                'tiene_caducidad' => false,
            ],
            [
                'categoria' => 'Rehabilitacion',
                'proveedor' => 'Terapia Avanzada',
                'nombre' => 'Almohada Cojin Inflable Cuello Relajante Viaje',
                'sku' => 'REHAB-COJ-001',
                'codigo_barras' => '7501001000158',
                'unidad_medida' => 'pieza',
                'precio_compra' => 243.00,
                'precio_venta' => 430.00,
                'stock_actual' => 18,
                'stock_minimo' => 8,
                'tiene_caducidad' => false,
            ],
            [
                'categoria' => 'Equipos Respiratorios',
                'proveedor' => 'Equipos Respiratorios Pro',
                'nombre' => 'Agua Bidestilada 10 Lts Desionizada Para Equipo Respiratorio',
                'sku' => 'RES-AGUA-001',
                'codigo_barras' => '7501001000165',
                'unidad_medida' => 'pieza',
                'precio_compra' => 162.00,
                'precio_venta' => 239.00,
                'stock_actual' => 22,
                'stock_minimo' => 10,
                'tiene_caducidad' => true,
            ],
            [
                'categoria' => 'Equipos Respiratorios',
                'proveedor' => 'Equipos Respiratorios Pro',
                'nombre' => 'Aspirador De Secreciones Profesional Drive Medical',
                'sku' => 'RES-ASP-001',
                'codigo_barras' => '7501001000172',
                'unidad_medida' => 'pieza',
                'precio_compra' => 6360.00,
                'precio_venta' => 8999.00,
                'stock_actual' => 3,
                'stock_minimo' => 1,
                'tiene_caducidad' => false,
            ],
            [
                'categoria' => 'Audicion y Comunicacion',
                'proveedor' => 'Audición Plus',
                'nombre' => 'Audifono Amplificador Auxiliar Auditivo Recargable',
                'sku' => 'AUD-AMP-001',
                'codigo_barras' => '7501001000189',
                'unidad_medida' => 'pieza',
                'precio_compra' => 2914.00,
                'precio_venta' => 3499.00,
                'stock_actual' => 6,
                'stock_minimo' => 3,
                'tiene_caducidad' => false,
            ],
            [
                'categoria' => 'Cuidado Domiciliario',
                'proveedor' => 'MedSupply Central',
                'nombre' => 'Asa Punio Agarradera Para Vaso Taza Botellas Lujo',
                'sku' => 'CUI-ASA-001',
                'codigo_barras' => '7501001000196',
                'unidad_medida' => 'pieza',
                'precio_compra' => 99.00,
                'precio_venta' => 120.00,
                'stock_actual' => 35,
                'stock_minimo' => 15,
                'tiene_caducidad' => false,
            ],
        ];

        foreach ($productos as $index => $producto) {
            $imagenPath = $producto['imagen_path'] ?? $imagenes[$index % count($imagenes)];
            DB::table('productos')->updateOrInsert(
                ['sku' => $producto['sku']],
                [
                    'categoria_id' => $categoriaIds[$producto['categoria']] ?? null,
                    'proveedor_id' => $proveedorIds[$producto['proveedor']] ?? null,
                    'nombre' => $producto['nombre'],
                    'codigo_barras' => $producto['codigo_barras'] ?? null,
                    'unidad_medida' => $producto['unidad_medida'] ?? 'pieza',
                    'fecha_caducidad' => $producto['tiene_caducidad'] ? now()->addMonths(18)->toDateString() : null,
                    'imagen_path' => $imagenPath,
                    'descripcion' => null,
                    'precio_compra' => $producto['precio_compra'],
                    'precio_venta' => $producto['precio_venta'],
                    'stock_actual' => $producto['stock_actual'],
                    'stock_minimo' => $producto['stock_minimo'],
                    'tiene_caducidad' => $producto['tiene_caducidad'],
                    'activo' => true,
                    'updated_at' => now(),
                    'created_at' => now(),
                ]
            );
        }
    }
}
